# Generated by Django 3.0.1 on 2019-12-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NonFrozen', '0003_auto_20191227_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Weight',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
    ]
