# Generated by Django 3.0.1 on 2019-12-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NonFrozen', '0004_auto_20191227_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Weight',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
