# Generated by Django 3.0.1 on 2019-12-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NonFrozen', '0005_auto_20191227_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Thumb',
            field=models.ImageField(blank=True, default='NonFrozen/Belly.jpg', upload_to=''),
        ),
    ]
