# Generated by Django 3.0.1 on 2019-12-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NonFrozen', '0006_product_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
