# Generated by Django 3.0.1 on 2019-12-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frozen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
