# Generated by Django 3.0.1 on 2019-12-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frozen', '0002_auto_20191226_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
